"""retry

Revision ID: 049a19a369f5
Revises: 5d3e73d38caa
Create Date: 2025-06-16 11:39:01.467842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049a19a369f5'
down_revision = '5d3e73d38caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_value', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('credit_value')

    # ### end Alembic commands ###
