"""Initial schema

Revision ID: 0c5157c2782b
Revises: 
Create Date: 2026-08-27 00:53:42.175503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5157c2782b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('pickup_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('profile_picture', sa.String(length=200), nullable=True),
    sa.Column('nin', sa.String(length=20), nullable=True),
    sa.Column('government_id_document', sa.String(length=255), nullable=True),
    sa.Column('id_verification_status', sa.String(length=30), nullable=False),
    sa.Column('id_verified_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('first_login', sa.Boolean(), nullable=True),
    sa.Column('last_checkout_transaction_id', sa.String(length=8), nullable=True),
    sa.Column('last_checkout_timestamp', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('profile_completed_at', sa.DateTime(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('trading_points', sa.Integer(), nullable=True),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referral_bonus_earned', sa.Integer(), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('ban_date', sa.DateTime(), nullable=True),
    sa.Column('unban_requested', sa.Boolean(), nullable=True),
    sa.Column('unban_request_date', sa.DateTime(), nullable=True),
    sa.Column('appeal_message', sa.Text(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=True),
    sa.Column('password_change_required', sa.Boolean(), nullable=True),
    sa.Column('data_export_requested', sa.Boolean(), nullable=True),
    sa.Column('data_export_date', sa.DateTime(), nullable=True),
    sa.Column('account_deletion_requested', sa.Boolean(), nullable=True),
    sa.Column('account_deletion_date', sa.DateTime(), nullable=True),
    sa.Column('gdpr_consent_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('notification_preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_verification_token'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_email_verified'), ['email_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_profile_completed'), ['profile_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_activity_log_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('idx_cart_user_id', ['user_id'], unique=False)

    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index('idx_contact_message_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_contact_message_status', ['status'], unique=False)
        batch_op.create_index('idx_contact_message_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_status'), ['status'], unique=False)

    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=300), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('usage_duration', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('item_number', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], name='fk_item_uploader'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_item_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_number')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.create_index('idx_item_category', ['category'], unique=False)
        batch_op.create_index('idx_item_category_available', ['category', 'is_available'], unique=False)
        batch_op.create_index('idx_item_is_available', ['is_available'], unique=False)
        batch_op.create_index('idx_item_status', ['status'], unique=False)
        batch_op.create_index('idx_item_user_id', ['user_id'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_email_sent', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_method', sa.String(length=20), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('date_ordered', sa.DateTime(), nullable=True),
    sa.Column('pickup_station_id', sa.Integer(), nullable=True),
    sa.Column('cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('total_credits', sa.Float(), nullable=True),
    sa.Column('credits_used', sa.Float(), nullable=True),
    sa.Column('credits_balance_before', sa.Float(), nullable=True),
    sa.Column('credits_balance_after', sa.Float(), nullable=True),
    sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('receipt_downloaded', sa.Boolean(), nullable=True),
    sa.Column('transaction_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pickup_station_id'], ['pickup_station.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_number')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('monnify_reference', sa.String(length=255), nullable=True),
    sa.Column('paystack_reference', sa.String(length=255), nullable=True),
    sa.Column('amount_naira', sa.Float(), nullable=False),
    sa.Column('credits_purchased', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('customer_email', sa.String(length=120), nullable=True),
    sa.Column('customer_phone', sa.String(length=15), nullable=True),
    sa.Column('payment_metadata', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_monnify_reference'), ['monnify_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_paystack_reference'), ['paystack_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_user_id'), ['user_id'], unique=False)

    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code_used', sa.String(length=20), nullable=False),
    sa.Column('signup_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('signup_bonus_earned_at', sa.DateTime(), nullable=True),
    sa.Column('item_upload_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('purchase_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('item_upload_bonus_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_bonus_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remember_device', sa.Boolean(), nullable=True),
    sa.Column('trusted_devices', sa.JSON(), nullable=True),
    sa.Column('alert_on_new_device', sa.Boolean(), nullable=True),
    sa.Column('alert_on_location_change', sa.Boolean(), nullable=True),
    sa.Column('password_strength_required', sa.String(length=20), nullable=True),
    sa.Column('ip_whitelist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_security_settings_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('maintenance_enabled_by', sa.Integer(), nullable=True),
    sa.Column('maintenance_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('allow_uploads', sa.Boolean(), nullable=True),
    sa.Column('allow_trading', sa.Boolean(), nullable=True),
    sa.Column('allow_browsing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_enabled_by'], ['admin.id'], name='fk_maintenance_admin'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_maintenance_mode'), ['maintenance_mode'], unique=False)

    op.create_table('user_gamification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('trading_points', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referral_bonus_earned', sa.Integer(), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_gamification_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_gamification_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_gamification_user_id'), ['user_id'], unique=True)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=False),
    sa.Column('password_change_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_security_user_id'), ['user_id'], unique=True)

    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notify_via_email', sa.Boolean(), nullable=True),
    sa.Column('notify_via_app', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_name', 'search_type', name='unique_wishlist_item')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index('idx_wishlist_active', ['is_active'], unique=False)
        batch_op.create_index('idx_wishlist_category', ['category'], unique=False)
        batch_op.create_index('idx_wishlist_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)

    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'item_id', name='unique_cart_item')
    )
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.create_index('idx_cartitem_cart_id', ['cart_id'], unique=False)

    op.create_table('credit_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('balance_before', sa.Float(), nullable=True),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('related_order_id', sa.Integer(), nullable=True),
    sa.Column('related_item_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['related_order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='unique_user_favorite')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index('idx_favorite_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_favorite_user_id', ['user_id'], unique=False)

    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('quality_flags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_given_id', sa.Integer(), nullable=True),
    sa.Column('item_received_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_given_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['item_received_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.create_index('idx_trade_receiver_id', ['receiver_id'], unique=False)
        batch_op.create_index('idx_trade_sender_id', ['sender_id'], unique=False)
        batch_op.create_index('idx_trade_status', ['status'], unique=False)

    op.create_table('wishlist_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('app_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'item_id', name='unique_wishlist_match')
    )
    with op.batch_alter_table('wishlist_match', schema=None) as batch_op:
        batch_op.create_index('idx_wishlist_match_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_wishlist_match_wishlist_id', ['wishlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_match_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_match_wishlist_id'), ['wishlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_match_wishlist_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_match_item_id'))
        batch_op.drop_index('idx_wishlist_match_wishlist_id')
        batch_op.drop_index('idx_wishlist_match_item_id')

    op.drop_table('wishlist_match')
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_index('idx_trade_status')
        batch_op.drop_index('idx_trade_sender_id')
        batch_op.drop_index('idx_trade_receiver_id')

    op.drop_table('trade')
    op.drop_table('order_item')
    op.drop_table('item_image')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index('idx_favorite_user_id')
        batch_op.drop_index('idx_favorite_item_id')

    op.drop_table('favorite')
    op.drop_table('credit_transaction')
    with op.batch_alter_table('cart_item', schema=None) as batch_op:
        batch_op.drop_index('idx_cartitem_cart_id')

    op.drop_table('cart_item')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_is_active'))
        batch_op.drop_index(batch_op.f('ix_wishlist_created_at'))
        batch_op.drop_index('idx_wishlist_user_id')
        batch_op.drop_index('idx_wishlist_category')
        batch_op.drop_index('idx_wishlist_active')

    op.drop_table('wishlist')
    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_security_user_id'))

    op.drop_table('user_security')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_gamification_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_gamification_tier'))
        batch_op.drop_index(batch_op.f('ix_user_gamification_level'))

    op.drop_table('user_gamification')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_maintenance_mode'))

    op.drop_table('system_settings')
    op.drop_table('security_settings')
    op.drop_table('referral')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_user_id'))
        batch_op.drop_index(batch_op.f('ix_payment_status'))
        batch_op.drop_index(batch_op.f('ix_payment_paystack_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_monnify_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_created_at'))

    op.drop_table('payment')
    op.drop_table('order')
    op.drop_table('notification')
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_index('idx_item_user_id')
        batch_op.drop_index('idx_item_status')
        batch_op.drop_index('idx_item_is_available')
        batch_op.drop_index('idx_item_category_available')
        batch_op.drop_index('idx_item_category')

    op.drop_table('item')
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_status'))
        batch_op.drop_index(batch_op.f('ix_contact_message_name'))
        batch_op.drop_index(batch_op.f('ix_contact_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))
        batch_op.drop_index(batch_op.f('ix_contact_message_created_at'))
        batch_op.drop_index('idx_contact_message_user_id')
        batch_op.drop_index('idx_contact_message_status')
        batch_op.drop_index('idx_contact_message_created_at')

    op.drop_table('contact_message')
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('idx_cart_user_id')

    op.drop_table('cart')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_admin_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_type'))

    op.drop_table('audit_log')
    op.drop_table('activity_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tier'))
        batch_op.drop_index(batch_op.f('ix_user_profile_completed'))
        batch_op.drop_index(batch_op.f('ix_user_level'))
        batch_op.drop_index(batch_op.f('ix_user_is_banned'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_email_verified'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('pickup_station')
    op.drop_table('admin')
    # ### end Alembic commands ###
