"""Add missing ban and appeal columns to User model

Revision ID: 119211f50d0a
Revises: 4975c37b4aa2
Create Date: 2026-02-09 19:32:16.368656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '119211f50d0a'
down_revision = '4975c37b4aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_activity_log_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referral_code_used', sa.String(length=20), nullable=False),
    sa.Column('signup_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('item_upload_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('purchase_bonus_earned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('item_upload_bonus_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_bonus_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('remember_device', sa.Boolean(), nullable=True),
    sa.Column('trusted_devices', sa.JSON(), nullable=True),
    sa.Column('alert_on_new_device', sa.Boolean(), nullable=True),
    sa.Column('alert_on_location_change', sa.Boolean(), nullable=True),
    sa.Column('password_strength_required', sa.String(length=20), nullable=True),
    sa.Column('ip_whitelist', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_security_settings_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_gamification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('trading_points', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referral_bonus_earned', sa.Integer(), nullable=False),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_gamification_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_gamification_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_gamification_user_id'), ['user_id'], unique=True)

    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_preferences', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_preferences_user_id'), ['user_id'], unique=True)

    op.create_table('user_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('two_factor_secret', sa.String(length=32), nullable=True),
    sa.Column('last_password_change', sa.DateTime(), nullable=False),
    sa.Column('password_change_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_security_user_id'), ['user_id'], unique=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_audit_log_admin_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_audit_log_admin_id_admin', 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('unban_request_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('appeal_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('appeal_message')
        batch_op.drop_column('unban_request_date')
        batch_op.drop_column('ban_date')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_log_admin_id_admin', type_='foreignkey')
        batch_op.create_foreign_key('fk_audit_log_admin_id_admin', 'user', ['admin_id'], ['id'])

    with op.batch_alter_table('user_security', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_security_user_id'))

    op.drop_table('user_security')
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_preferences_user_id'))

    op.drop_table('user_preferences')
    with op.batch_alter_table('user_gamification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_gamification_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_gamification_tier'))
        batch_op.drop_index(batch_op.f('ix_user_gamification_level'))

    op.drop_table('user_gamification')
    op.drop_table('security_settings')
    op.drop_table('referral')
    op.drop_table('activity_log')
    # ### end Alembic commands ###
