"""item image table

Revision ID: 159366ca4c97
Revises: fe6d1cec4ac2
Create Date: 2025-08-25 14:18:28.186885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159366ca4c97'
down_revision = 'fe6d1cec4ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=300), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=300), nullable=True))

    op.drop_table('item_image')
    # ### end Alembic commands ###
