"""Add ban fields to User model

Revision ID: 166b07fee974
Revises: 63660db42fe5
Create Date: 2025-08-09 15:14:40.581241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166b07fee974'
down_revision = '63660db42fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ban_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('unban_requested', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('unban_requested')
        batch_op.drop_column('ban_reason')

    # ### end Alembic commands ###
