"""credited

Revision ID: 19036deae963
Revises: eb05198b7a81
Create Date: 2025-06-25 10:16:56.546568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19036deae963'
down_revision = 'eb05198b7a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credited', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('credited')

    # ### end Alembic commands ###
