"""added tier field to user models

Revision ID: 1d192d8d6a7d
Revises: 79317f10eb66
Create Date: 2025-12-12 19:32:21.337771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d192d8d6a7d'
down_revision = '79317f10eb66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add tier column to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True, server_default='Beginner'))

    # Set default value for any existing users
    op.execute("UPDATE user SET tier = 'Beginner' WHERE tier IS NULL")

    # Make tier NOT NULL after setting defaults
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('tier', existing_type=sa.String(length=20), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tier')

    # ### end Alembic commands ###
    # ### end Alembic commands ###
