"""add description column to credit_transaction table

Revision ID: 2e9bd8d01020
Revises: 84a3275df4f2
Create Date: 2026-01-02 18:22:00.816168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e9bd8d01020'
down_revision = '84a3275df4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reason', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('balance_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('balance_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('related_order_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('related_item_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_credit_transaction_related_order_id', 'order', ['related_order_id'], ['id'])
        batch_op.create_foreign_key('fk_credit_transaction_related_item_id', 'item', ['related_item_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Beginner'"))
        batch_op.alter_column('trading_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('referral_bonus_earned',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('referral_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_admin'), ['is_admin'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_tier'), ['tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)
        batch_op.create_unique_constraint('uq_user_email_verification_token', ['email_verification_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email_verification_token', type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_tier'))
        batch_op.drop_index(batch_op.f('ix_user_level'))
        batch_op.drop_index(batch_op.f('ix_user_is_banned'))
        batch_op.drop_index(batch_op.f('ix_user_is_admin'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('referral_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('referral_bonus_earned',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('trading_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Beginner'"))
        batch_op.alter_column('level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credit_transaction_related_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_credit_transaction_related_order_id', type_='foreignkey')
        batch_op.drop_column('related_item_id')
        batch_op.drop_column('related_order_id')
        batch_op.drop_column('balance_after')
        batch_op.drop_column('balance_before')
        batch_op.drop_column('reason')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
