"""migration

Revision ID: 432a8a262cb7
Revises: ea42ceca75be
Create Date: 2025-06-13 10:47:20.167466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '432a8a262cb7'
down_revision = 'ea42ceca75be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_banned', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_banned')

    # ### end Alembic commands ###
