"""Add Wishlist and WishlistMatch models for user watchlist feature

Revision ID: 4975c37b4aa2
Revises: 9dcdce4c8ea4
Create Date: 2026-02-09 19:08:43.077382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4975c37b4aa2'
down_revision = '9dcdce4c8ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notify_via_email', sa.Boolean(), nullable=True),
    sa.Column('notify_via_app', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_name', 'search_type', name='unique_wishlist_item')
    )
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.create_index('idx_wishlist_active', ['is_active'], unique=False)
        batch_op.create_index('idx_wishlist_category', ['category'], unique=False)
        batch_op.create_index('idx_wishlist_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_user_id'), ['user_id'], unique=False)

    op.create_table('wishlist_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('app_notification_sent', sa.Boolean(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wishlist_id', 'item_id', name='unique_wishlist_match')
    )
    with op.batch_alter_table('wishlist_match', schema=None) as batch_op:
        batch_op.create_index('idx_wishlist_match_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_wishlist_match_wishlist_id', ['wishlist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_match_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wishlist_match_wishlist_id'), ['wishlist_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_match_wishlist_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_match_item_id'))
        batch_op.drop_index('idx_wishlist_match_wishlist_id')
        batch_op.drop_index('idx_wishlist_match_item_id')

    op.drop_table('wishlist_match')
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wishlist_user_id'))
        batch_op.drop_index(batch_op.f('ix_wishlist_is_active'))
        batch_op.drop_index(batch_op.f('ix_wishlist_created_at'))
        batch_op.drop_index('idx_wishlist_user_id')
        batch_op.drop_index('idx_wishlist_category')
        batch_op.drop_index('idx_wishlist_active')

    op.drop_table('wishlist')
    # ### end Alembic commands ###
