"""Add SystemSettings model for maintenance mode

Revision ID: 6c95d38d4741
Revises: 2e9bd8d01020
Create Date: 2026-01-02 19:03:51.609750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c95d38d4741'
down_revision = '2e9bd8d01020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('maintenance_message', sa.Text(), nullable=True),
    sa.Column('maintenance_enabled_by', sa.Integer(), nullable=True),
    sa.Column('maintenance_enabled_at', sa.DateTime(), nullable=True),
    sa.Column('allow_uploads', sa.Boolean(), nullable=True),
    sa.Column('allow_trading', sa.Boolean(), nullable=True),
    sa.Column('allow_browsing', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_enabled_by'], ['admin.id'], name='fk_maintenance_admin'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_maintenance_mode'), ['maintenance_mode'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_maintenance_mode'))

    op.drop_table('system_settings')
    # ### end Alembic commands ###
