"""Add ContactMessage model

Revision ID: 76814375cdb2
Revises: 119211f50d0a
Create Date: 2026-02-13 09:18:37.622551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76814375cdb2'
down_revision = '119211f50d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('response_sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index('idx_contact_message_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_contact_message_status', ['status'], unique=False)
        batch_op.create_index('idx_contact_message_user_id', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_status'))
        batch_op.drop_index(batch_op.f('ix_contact_message_name'))
        batch_op.drop_index(batch_op.f('ix_contact_message_is_read'))
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))
        batch_op.drop_index(batch_op.f('ix_contact_message_created_at'))
        batch_op.drop_index('idx_contact_message_user_id')
        batch_op.drop_index('idx_contact_message_status')
        batch_op.drop_index('idx_contact_message_created_at')

    op.drop_table('contact_message')
    # ### end Alembic commands ###
