"""Add account security, GDPR, and activity logging features

Revision ID: 782deb8fac69
Revises: 8e2221ad629a
Create Date: 2025-12-07 03:28:58.375525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '782deb8fac69'
down_revision = '8e2221ad629a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_credits', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('credits_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('credits_balance_before', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('credits_balance_after', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('actual_delivery_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('receipt_downloaded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('transaction_notes', sa.Text(), nullable=True))
        batch_op.create_unique_constraint('uq_order_order_number', ['order_number'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('two_factor_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_change_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_export_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_export_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_deletion_requested', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('account_deletion_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('gdpr_consent_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('gdpr_consent_date')
        batch_op.drop_column('account_deletion_date')
        batch_op.drop_column('account_deletion_requested')
        batch_op.drop_column('data_export_date')
        batch_op.drop_column('data_export_requested')
        batch_op.drop_column('password_change_required')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('two_factor_secret')
        batch_op.drop_column('two_factor_enabled')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('transaction_notes')
        batch_op.drop_column('receipt_downloaded')
        batch_op.drop_column('actual_delivery_date')
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('credits_balance_after')
        batch_op.drop_column('credits_balance_before')
        batch_op.drop_column('credits_used')
        batch_op.drop_column('total_credits')
        batch_op.drop_column('order_number')

    # ### end Alembic commands ###
