"""trade

Revision ID: 78f78d386b77
Revises: 19036deae963
Create Date: 2025-07-01 09:45:16.168982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f78d386b77'
down_revision = '19036deae963'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_given_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_received_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_trade_item_given', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_trade_item_received', 'item', ['item_given_id'], ['id'])
        batch_op.create_foreign_key('fk_trade_user', 'item', ['item_received_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('item_received_id')
        batch_op.drop_column('item_given_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
