"""Add gamification fields to User model

Revision ID: 79317f10eb66
Revises: 3ed17ab84b11
Create Date: 2025-12-08 13:51:33.250134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79317f10eb66'
down_revision = '3ed17ab84b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('trading_points', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('referral_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('referral_bonus_earned', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('referral_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.create_unique_constraint(None, ['referral_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('referral_count')
        batch_op.drop_column('referral_bonus_earned')
        batch_op.drop_column('referral_code')
        batch_op.drop_column('trading_points')
        batch_op.drop_column('level')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('order_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
