"""little changes

Revision ID: 8e2221ad629a
Revises: security_001
Create Date: 2025-12-07 01:49:20.452705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2221ad629a'
down_revision = 'security_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('action_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_preferences', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('notification_preferences')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('priority')
        batch_op.drop_column('is_email_sent')
        batch_op.drop_column('data')
        batch_op.drop_column('action_url')
        batch_op.drop_column('category')
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
