"""Add Favorites model

Revision ID: 9dcdce4c8ea4
Revises: 6c95d38d4741
Create Date: 2026-01-16 08:30:06.160084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcdce4c8ea4'
down_revision = '6c95d38d4741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='unique_user_favorite')
    )
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index('idx_favorite_item_id', ['item_id'], unique=False)
        batch_op.create_index('idx_favorite_user_id', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index('idx_favorite_user_id')
        batch_op.drop_index('idx_favorite_item_id')

    op.drop_table('favorite')
    # ### end Alembic commands ###

    op.drop_table('favorite')
    # ### end Alembic commands ###
