"""Add AI valuation fields

Revision ID: aa551f877817
Revises: 2edc53b7f671
Create Date: 2026-03-02 09:54:50.882867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa551f877817'
down_revision = '2edc53b7f671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_estimated_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_confidence', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ai_analysis', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_condition_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ai_market_listings', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('provisional_credit_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('provisional_credits_issued', sa.Boolean(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('provisional_credits_issued_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=30), nullable=True, server_default='pending_valuation'))
        batch_op.add_column(sa.Column('verified_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pickup_station_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('scheduled_pickup_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_result', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('final_credit_value', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_item_pickup_station', 'pickup_station', ['pickup_station_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_item_verified_by', 'user', ['verified_by_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_verified_by', type_='foreignkey')
        batch_op.drop_constraint('fk_item_pickup_station', type_='foreignkey')
        batch_op.drop_column('final_credit_value')
        batch_op.drop_column('verification_result')
        batch_op.drop_column('scheduled_pickup_date')
        batch_op.drop_column('pickup_station_id')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by_id')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('provisional_credits_issued_at')
        batch_op.drop_column('provisional_credits_issued')
        batch_op.drop_column('provisional_credit_value')
        batch_op.drop_column('ai_market_listings')
        batch_op.drop_column('ai_condition_score')
        batch_op.drop_column('ai_analysis')
        batch_op.drop_column('ai_confidence')
        batch_op.drop_column('ai_estimated_value')

    # ### end Alembic commands ###
