"""Add checkout transaction tracking fields to user model

Revision ID: add_checkout_tracking
Revises: add_database_indexes
Create Date: 2025-12-24

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_checkout_tracking'
down_revision = 'add_database_indexes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checkout_transaction_id', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('last_checkout_timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_checkout_timestamp')
        batch_op.drop_column('last_checkout_transaction_id')

    # ### end Alembic commands ###
