"""pickup station

Revision ID: fe6d1cec4ac2
Revises: 60fd79514d67
Create Date: 2025-08-22 10:41:43.021162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe6d1cec4ac2'
down_revision = '60fd79514d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pickup_station', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
